#!/usr/bin/env bash
# Copyright (c) Nebari Development Team.
# Distributed under the terms of the Modified BSD License.

set -euo pipefail

# A workaround that allows a command to run in a
# specific pixi environment
cat <<EOF >/opt/conda-run-worker
#!/bin/bash
set -xe

pixi run --manifest-path /opt/dask-worker/ dask-worker "\$@"
EOF

cat <<EOF >/opt/conda-run-scheduler
#!/bin/bash
set -xe

pixi run --manifest-path /opt/dask-worker/ dask-scheduler "\$@"
EOF

chmod 755 /opt/conda-run-worker
chmod 755 /opt/conda-run-scheduler
